// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projetStage.Server;

#nullable disable

namespace projetStage.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250525182314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projetStage.Server.Models.Circonscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PrefectureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrefectureId");

                    b.ToTable("Circonscriptions");
                });

            modelBuilder.Entity("projetStage.Server.Models.DashboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CirconscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("NombreBureaux")
                        .HasColumnType("int");

                    b.Property<int>("NombreListes")
                        .HasColumnType("int");

                    b.Property<int>("NombreSieges")
                        .HasColumnType("int");

                    b.Property<int>("PrefectureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("entryId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CirconscriptionId");

                    b.HasIndex("PrefectureId");

                    b.HasIndex("UserId");

                    b.ToTable("DashboardEntries");
                });

            modelBuilder.Entity("projetStage.Server.Models.Prefecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Prefectures");
                });

            modelBuilder.Entity("projetStage.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("projetStage.Server.Models.Circonscription", b =>
                {
                    b.HasOne("projetStage.Server.Models.Prefecture", "Prefecture")
                        .WithMany("Circonscriptions")
                        .HasForeignKey("PrefectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prefecture");
                });

            modelBuilder.Entity("projetStage.Server.Models.DashboardEntry", b =>
                {
                    b.HasOne("projetStage.Server.Models.Circonscription", "Circonscription")
                        .WithMany("DashboardEntries")
                        .HasForeignKey("CirconscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projetStage.Server.Models.Prefecture", "Prefecture")
                        .WithMany("DashboardEntries")
                        .HasForeignKey("PrefectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projetStage.Server.Models.User", "User")
                        .WithMany("DashboardEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circonscription");

                    b.Navigation("Prefecture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projetStage.Server.Models.Circonscription", b =>
                {
                    b.Navigation("DashboardEntries");
                });

            modelBuilder.Entity("projetStage.Server.Models.Prefecture", b =>
                {
                    b.Navigation("Circonscriptions");

                    b.Navigation("DashboardEntries");
                });

            modelBuilder.Entity("projetStage.Server.Models.User", b =>
                {
                    b.Navigation("DashboardEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
